[project]
name = "ember-ai"
version = "0.1.0"
description = "Compositional framework for building AI systems"
requires-python = ">=3.9"

# Minimal dependencies for testing
dependencies = [
    # Core essentials only
    "pydantic>=2.7.4",
    "pydantic-core>=2.18.4",
    "PyYAML>=6.0.1",
    "typing_extensions>=4.12.2",
    
    # HTTP essentials
    "aiohttp>=3.9.5",
    "httpx>=0.27.0",
    "requests>=2.32.2",
    
    # Testing
    "pytest>=7.4.4",
]

[project.optional-dependencies]
# Full dependencies
full = [
    "openai>=1.57.2",
    "anthropic>=0.40.0",
    "google-generativeai>=0.8.3",
    "pandas>=1.0.0,<2.2.0",
    "numpy>=1.21.0,<1.27.0",
    "psutil>=5.9.0",
]

# JAX for advanced features
jax = [
    "jax>=0.4.0",
    "equinox>=0.11.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"